import { transaction } from "@/app/types/transaction";

export const MOCK_TRANSACTION: transaction[] = [
  {
    id: "1",
    amount: 12.5,
    date: "2024-11-20",
    description: "Coffee with friends",
    type: "Credit Card",
    status: "Successful",
    category: "Beverage",
  },
  {
    id: "2",
    amount: 45.99,
    date: "2024-11-19",
    description: "Lunch at Italian Bistro",
    type: "Debit Card",
    status: "Successful",
    category: "Meal",
  },
  {
    id: "3",
    amount: 750.0,
    date: "2024-11-18",
    description: "Monthly rental payment",
    type: "Debit Card",
    category: "Rental",
  },
  {
    id: "4",
    amount: 20.0,
    date: "2024-11-17",
    description: "Basketball court booking",
    type: "FPX",
    status: "Pending",
    category: "Sport",
  },
  {
    id: "5",
    amount: 15.0,
    date: "2024-11-16",
    description: "Gift for colleague",
    type: "Debit Card",
    status: "Failed",
    category: "Gift",
  },
  {
    id: "6",
    amount: 100.0,
    date: "2024-11-15",
    description: "Car maintenance",
    type: "Credit Card",
    category: "Maintenance",
  },
  {
    id: "7",
    amount: 30.0,
    date: "2024-11-14",
    description: "New book purchase",
    type: "FPX",
    status: "Successful",
    category: "Book",
  },
  {
    id: "8",
    amount: 200.0,
    date: "2024-11-13",
    description: "Doctor visit",
    type: "Debit Card",
    status: "Successful",
    category: "Medical",
  },
  {
    id: "9",
    amount: 5.5,
    date: "2024-11-12",
    description: "Taxi fare",
    type: "Debit Card",
    category: "Transport",
  },
  {
    id: "10",
    amount: 25.0,
    date: "2024-11-11",
    description: "Dinner with family",
    type: "FPX",
    status: "Successful",
    category: "Meal",
  },
  {
    id: "11",
    amount: 55.0,
    date: "2024-11-10",
    description: "Groceries shopping",
    type: "Credit Card",
    category: "Meal",
  },
  {
    id: "12",
    amount: 80.0,
    date: "2024-11-09",
    description: "Gym membership renewal",
    type: "Debit Card",
    status: "Pending",
    category: "Sport",
  },
  {
    id: "13",
    amount: 45.0,
    date: "2024-11-08",
    description: "Online course purchase",
    type: "Credit Card",
    category: "Book",
  },
  {
    id: "14",
    amount: 18.5,
    date: "2024-11-07",
    description: "Lunch at work",
    type: "Debit Card",
    status: "Successful",
    category: "Meal",
  },
  {
    id: "15",
    amount: 90.0,
    date: "2024-11-06",
    description: "Movie tickets for family",
    type: "FPX",
    category: "Leisure",
  },
  {
    id: "16",
    amount: 150.0,
    date: "2024-11-05",
    description: "Car tire replacement",
    type: "Credit Card",
    category: "Maintenance",
  },
  {
    id: "17",
    amount: 25.0,
    date: "2024-11-04",
    description: "Monthly library membership",
    type: "Credit Card",
    category: "Book",
  },
  {
    id: "18",
    amount: 300.0,
    date: "2024-11-03",
    description: "Yearly insurance premium",
    type: "Credit Card",
    status: "Successful",
    category: "Medical",
  },
  {
    id: "19",
    amount: 60.0,
    date: "2024-11-02",
    description: "Fitness equipment",
    type: "Debit Card",
    category: "Sport",
  },
  {
    id: "20",
    amount: 40.0,
    date: "2024-11-01",
    description: "Dinner at fancy restaurant",
    type: "Credit Card",
    status: "Failed",
    category: "Meal",
  },
  {
    id: "21",
    amount: 12.0,
    date: "2024-10-31",
    description: "Morning coffee",
    type: "Debit Card",
    category: "Beverage",
  },
  {
    id: "22",
    amount: 75.0,
    date: "2024-10-30",
    description: "Gift for a friend",
    type: "Credit Card",
    status: "Successful",
    category: "Gift",
  },
  {
    id: "23",
    amount: 500.0,
    date: "2024-10-29",
    description: "Monthly house rent",
    type: "Credit Card",
    category: "Rental",
  },
  {
    id: "24",
    amount: 20.0,
    date: "2024-10-28",
    description: "Taxi fare to office",
    type: "FPX",
    status: "Successful",
    category: "Transport",
  },
  {
    id: "25",
    amount: 80.0,
    date: "2024-10-27",
    description: "Sport equipment purchase",
    type: "Credit Card",
    category: "Sport",
  },
  {
    id: "26",
    amount: 65.0,
    date: "2024-10-26",
    description: "Dinner with colleagues",
    type: "Credit Card",
    status: "Successful",
    category: "Meal",
  },
  {
    id: "27",
    amount: 10.0,
    date: "2024-10-25",
    description: "New book for study",
    type: "FPX",
    category: "Book",
  },
  {
    id: "28",
    amount: 100.0,
    date: "2024-10-24",
    description: "Medication purchase",
    type: "FPX",
    status: "Successful",
    category: "Medical",
  },
  {
    id: "29",
    amount: 200.0,
    date: "2024-10-23",
    description: "Car repair",
    type: "FPX",
    category: "Maintenance",
  },
  {
    id: "30",
    amount: 50.0,
    date: "2024-10-22",
    description: "Dinner at local restaurant",
    type: "FPX",
    category: "Meal",
  },
  {
    id: "31",
    amount: 25.0,
    date: "2024-10-21",
    description: "Lunch with teammates",
    type: "FPX",
    category: "Meal",
  },
  {
    id: "32",
    amount: 500.0,
    date: "2024-10-20",
    description: "Rental payment for parking",
    type: "Credit Card",
    category: "Rental",
  },
  {
    id: "33",
    amount: 10.5,
    date: "2024-10-19",
    description: "Morning tea with snack",
    type: "Credit Card",
    category: "Beverage",
  },
  {
    id: "34",
    amount: 300.0,
    date: "2024-10-18",
    description: "Travel ticket booking",
    type: "Credit Card",
    category: "Transport",
  },
  {
    id: "35",
    amount: 60.0,
    date: "2024-10-17",
    description: "Books for self-study",
    type: "Credit Card",
    category: "Book",
  },
  {
    id: "36",
    amount: 50.0,
    date: "2024-10-16",
    description: "Medicine for flu",
    type: "Debit Card",
    category: "Medical",
  },
  {
    id: "37",
    amount: 45.0,
    date: "2024-10-15",
    description: "Groceries",
    type: "Debit Card",
    category: "Meal",
  },
  {
    id: "38",
    amount: 250.0,
    date: "2024-10-14",
    description: "Sport coaching fees",
    type: "Credit Card",
    category: "Sport",
  },
  {
    id: "39",
    amount: 12.5,
    date: "2024-10-13",
    description: "Coffee with partner",
    type: "Debit Card",
    category: "Beverage",
  },
  {
    id: "40",
    amount: 350.0,
    date: "2024-10-12",
    description: "Rental payment for warehouse",
    type: "Debit Card",
    category: "Rental",
  },
  {
    id: "41",
    amount: 15.0,
    date: "2024-10-11",
    description: "Evening snack",
    type: "Debit Card",
    category: "Meal",
  },
  {
    id: "42",
    amount: 50.0,
    date: "2024-10-10",
    description: "Sport jersey purchase",
    type: "Debit Card",
    category: "Sport",
  },
  {
    id: "43",
    amount: 120.0,
    date: "2024-10-09",
    description: "Car oil change",
    type: "Debit Card",
    category: "Maintenance",
  },
  {
    id: "44",
    amount: 8.0,
    date: "2024-10-08",
    description: "Coffee from cafe",
    type: "FPX",
    category: "Beverage",
  },
  {
    id: "45",
    amount: 500.0,
    date: "2024-10-07",
    description: "Monthly rental payment",
    type: "FPX",
    category: "Rental",
  },
  {
    id: "46",
    amount: 18.0,
    date: "2024-10-06",
    description: "Morning breakfast",
    type: "FPX",
    category: "Meal",
  },
  {
    id: "47",
    amount: 40.0,
    date: "2024-10-05",
    description: "Taxi to airport",
    type: "FPX",
    category: "Transport",
  },
  {
    id: "48",
    amount: 20.0,
    date: "2024-10-04",
    description: "Doctor consultation",
    type: "FPX",
    category: "Medical",
  },
  {
    id: "49",
    amount: 60.0,
    date: "2024-10-03",
    description: "Gift for partner",
    type: "FPX",
    category: "Gift",
  },
  {
    id: "50",
    amount: 10.0,
    date: "2024-10-02",
    description: "Afternoon tea",
    type: "Debit Card",
    category: "Beverage",
  },
];
